version: "3"
services:
  notea:
    image: "diamkil/notea:latest"
    container_name: arakkk-notea
    ports:
      - "3000:3011"
      - "9000:9011"                # <Host>:<Container>
    environment:
      - PASSWORD=k0usuk30922
      - STORE_USER=arakkk
      - STORE_PASSWORD=k0usuk30922
    volumes:
      - "/important_files/notea:/data"
    networks:
    - container-link

networks:
  default:
    external:
      name: bridge
  container-link:
    external:
      name: container_network
