version: "3"
services:
  notea:
    image: "diamkil/notea:latest"
    container_name: arakkk-notea
    ports:
      - "3011:3000"
      - "9011:9000"                # <Host>:<Container>
    environment:
      - PASSWORD=k0usuk30922
      - STORE_USER=arakkk
      - STORE_PASSWORD=k0usuk30922
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "10"

